# Generated by Django 5.2 on 2025-04-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('govern', '0001_initial'),
        ('map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='governancerole',
            name='ai_systems',
            field=models.ManyToManyField(related_name='governance_roles', to='map.aisystem'),
        ),
        migrations.AddField(
            model_name='governancestructure',
            name='members',
            field=models.ManyToManyField(related_name='governance_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='governancestructure',
            name='parent_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_structures', to='govern.governancestructure'),
        ),
        migrations.AddField(
            model_name='humanaioversight',
            name='ai_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oversight_records', to='map.aisystem'),
        ),
        migrations.AddField(
            model_name='humanaioversight',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govern.governancerole'),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='governancestructure',
            name='policies',
            field=models.ManyToManyField(related_name='governing_structures', to='govern.policy'),
        ),
        migrations.AddField(
            model_name='riskappetite',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='policies',
            field=models.ManyToManyField(related_name='assigned_roles', to='govern.policy'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='ai_rmf_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thirdpartyoversight',
            name='oversight_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overseen_parties', to='govern.governancestructure'),
        ),
        migrations.AddField(
            model_name='thirdpartyrisk',
            name='ai_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_risks', to='map.aisystem'),
        ),
    ]
