# Generated by Django 5.2 on 2025-04-19 14:14

import django.db.models.deletion
import django.utils.timezone
import management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('measure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergentRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mitigation_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('MITIGATED', 'Mitigated'), ('ACCEPTED', 'Accepted')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('ai_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergent_risks', to='map.aisystem')),
                ('detected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=50)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('ai_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='map.aisystem')),
                ('emergent_risks', models.ManyToManyField(blank=True, to='management.emergentrisk')),
                ('lifecycle_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.lifecyclestage')),
                ('related_measurements', models.ManyToManyField(blank=True, to='measure.metricmeasurement')),
                ('related_risks', models.ManyToManyField(blank=True, to='map.riskidentification')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('trustworthiness_characteristics', models.ManyToManyField(blank=True, to='map.trustworthinesscharacteristic')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('ASSESSMENT', 'Assessment Finding'), ('INCIDENT', 'Incident Response'), ('METRIC', 'Metric Analysis'), ('STAKEHOLDER', 'Stakeholder Feedback')], max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=50)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(default=management.models.get_default_target_date)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('ai_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='map.aisystem')),
                ('related_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measure.assessment')),
                ('related_lifecycle_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.lifecyclestage')),
                ('related_trustworthiness', models.ManyToManyField(blank=True, to='map.trustworthinesscharacteristic')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.incident')),
            ],
        ),
        migrations.CreateModel(
            name='PostDeploymentMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_plan', models.TextField()),
                ('monitoring_metrics', models.TextField()),
                ('feedback_mechanisms', models.TextField()),
                ('incident_response_plan', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_deployment_monitoring', to='map.aisystem')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='post_deployment_monitoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.postdeploymentmonitoring'),
        ),
        migrations.CreateModel(
            name='RiskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('AVOID', 'Avoid Risk'), ('MITIGATE', 'Mitigate Risk'), ('TRANSFER', 'Transfer Risk'), ('ACCEPT', 'Accept Risk')], max_length=50)),
                ('description', models.TextField()),
                ('action_plan', models.TextField()),
                ('deadline', models.DateField(default=management.models.get_default_deadline)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='map.riskidentification')),
            ],
        ),
    ]
